name: "${{  vars.ORGANIZATION }}.prod"

on:
  push:
    branches:
      - prod
    paths:
      - "infra/**"
      - "!**/README.md"
  
  pull_request:
    branches:
      - staging
    paths:
      - "infra/**"
      - "!**/README.md"
