name: "${{ var.ORGANIZATION  }}.staging.infra"

on:
  push:
    branches:
      - staging
    paths:
      - "infra/**"
      - "!**/README.md"
  pull_request:
    branches:
      - staging
    paths:
      - "infra/**"
      - "!**/README.md"

jobs:
  terraform:
    name: "Terraform"
    runs-on:  ubuntu-latest
    defaults:
      run:
        working-directory:  "infra"
    steps:
      - name: Chekout
        uses: action/checkout@v3