name: Production

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"
      - "!**/README.md"
  
  pull_request:
    branches:
      - main
    paths:
      - "infra/**"
      - "!**/README.md"
