name: Developement

on:
   push:
     branches:
       - main
     paths:
       - "infra/**"
       - "!**/README.md"

env:
  orgs: "tomaszsielkigitops"

jobs:
  terraform:
    name: "Terraform"
    runs-on:  ubuntu-latest
    defaults:
      run:
        working-directory:  "infra"
    steps:
      - name: Chekout
        uses: action/checkout@v2
