name: Developement

on:
   push:
     branches:
       - main
     paths:
       - "infra/**"
       - "!**/README.md"

env:
  orgs: "tomaszsielkigitops"

jobs:
  terraform:
    name: "Terraform"
    runs-on:  ubuntu-latest
    defaults:
      run:
        working-directory:  "infra"
    steps:
      - name: Chekout
        uses: actions/checkout@v3

      - name: Uncomment Terraform Cloud Backend Configuration file
        id: uncomment
        run:  sed -i 's/^#*//' backend.tf
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version:  1.7.3
          cli_config_credentials_token:  ${{ secrets.TF_API_TOKEN  }}

      - name: Terraform Init
        id: init
        run:  terraform init -backend-config=dev.hcl
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
